# Generated by Django 5.1.1 on 2024-10-22 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_name', models.CharField(max_length=77)),
                ('project_desc', models.TextField(max_length=200)),
                ('project_members_count', models.IntegerField()),
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='team_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=78)),
                ('position', models.CharField(max_length=78)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
